"""empty message

Revision ID: 4cdf76253770
Revises: f828aecf1372
Create Date: 2018-04-14 15:39:41.496182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdf76253770'
down_revision = 'f828aecf1372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamescore', sa.Column('cluemax', sa.Integer(), nullable=True))
    op.add_column('gamescore', sa.Column('strikemax', sa.Integer(), nullable=True))
    op.drop_column('gamescore', 'playercount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamescore', sa.Column('playercount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('gamescore', 'strikemax')
    op.drop_column('gamescore', 'cluemax')
    # ### end Alembic commands ###
