"""empty message

Revision ID: f828aecf1372
Revises: fd59f7b5f605
Create Date: 2018-04-14 10:59:07.413649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f828aecf1372'
down_revision = 'fd59f7b5f605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamescore', sa.Column('handsize', sa.Integer(), nullable=True))
    op.add_column('gamescore', sa.Column('highestcard', sa.Integer(), nullable=True))
    op.add_column('gamescore', sa.Column('lettercount', sa.Integer(), nullable=True))
    op.add_column('gamescore', sa.Column('playercount', sa.Integer(), nullable=True))
    op.add_column('gamescore', sa.Column('strictness', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamescore', 'strictness')
    op.drop_column('gamescore', 'playercount')
    op.drop_column('gamescore', 'lettercount')
    op.drop_column('gamescore', 'highestcard')
    op.drop_column('gamescore', 'handsize')
    # ### end Alembic commands ###
